### ISSUE TITLE
trying this on debian squeeze and get: dpkg-checkbuilddeps: Unmet build dependencies: openssl (>= 1.0.0g)

### ISSUE THREAD

**Issue by kiranos** [mark-webster/node-debian#1]
Seems like its not compatible with current debian squeeze (stable) ?

ii  openssl                         0.9.8o-4squeeze14            Secure Socket Layer (SSL) binary and related cryptographic tools

**Comment by kiranos** [comment]
I edited deb/control to:

 openssl,

which made it work.

**Comment by mark-webster** [comment]
I've checked in the change.

Thanks for the feedback!
